### ISSUE TITLE
Error running `image_inference.py`

### ISSUE THREAD

**Issue by Ber666** [baaivision/Emu#31]
Hi, thanks for your great work!

I am running into a problem when trying to generate image with Emu.

```
Traceback (most recent call last):                                                                                       
  File "/home/shibo/Emu/image_inference.py", line 36, in <module>                                                        
    pipeline = EmuGenerationPipeline.from_pretrained(                                                                    
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                    
  File "/home/shibo/Emu/models/pipeline.py", line 254, in from_pretrained                                                
    return cls(                                                                                                          
           ^^^^                                                                                                          
  File "/home/shibo/Emu/models/pipeline.py", line 54, in __init__                                                        
    self.emu_encoder = self.prepare_emu("Emu-14B", multimodal_model, **kwargs)                                           
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                           
  File "/home/shibo/Emu/models/pipeline.py", line 232, in prepare_emu                                                    
    model.load_state_dict(ckpt, strict=True)                                                                             
  File "/home/shibo/anaconda3/envs/emu/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict                                                                                                                    
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(                                            
RuntimeError: Error(s) in loading state_dict for Emu:                                                                    
        Unexpected key(s) in state_dict: "decoder.lm.model.layers.0.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.1.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.2.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layer$.3.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.4.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.5.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.6.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.7.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.8.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.9.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.10.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.11.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.12.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.13.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.14.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.15.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.16.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.17.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.18.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.19.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.20.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.21.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.22.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.23.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.24.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.25.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.26.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.27.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.28.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.29.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.30.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.31.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.32.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.33.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.34.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.35.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.36.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.37.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.38.self_attn.rotary_emb.inv_freq", "decoder.lm.model.layers.39.self_attn.rotary_emb.inv_freq".
```

Do you have any ideas on the problem?

**Comment by ryanzhangfan** [comment]
The ```inv_freq``` is used in RoPE which is not a model parameter but is calculated when the class is instantiated. I guess that you might have installed the latest version of transformers which already [removed persistent  ```inv_freq``` tensor](https://github.com/huggingface/transformers/commit/95f96b45ffb57291c69a43d7a11a5bb166220d0b).

If so, you can simply skip loading these by setting [```strict=False```](https://github.com/baaivision/Emu/blob/278a106e73b733dc3881c1f375396c1ef04a6e17/models/pipeline.py#L232C29-L232C29)

**Comment by Ber666** [comment]
Thanks. That works for me.
